// Ultreia Camino Web V1 - hub + Control de Gastos + Seguimiento de Grupo
const HOME='homeView', EXP='expenseView', GROUP='groupView';
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(id).classList.add('active');if(id===GROUP&&window._map) setTimeout(()=>window._map.invalidateSize(),100)}
document.getElementById('goExpenses').onclick=()=>showView(EXP);document.getElementById('goGroup').onclick=()=>{showView(GROUP);renderGroup()};document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>showView(HOME));

// ---- Control de Gastos (misma lógica de la V7) ----
const KEY='ultreia-expenses-web-v1', concepts=['Desayuno','Comida','Cena','Dormir','Otros'], emojis={Desayuno:'🥐',Comida:'🥪',Cena:'🍽️',Dormir:'🛌',Otros:'🐚'};let state=loadExpense(),editingId=null;
function loadExpense(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return{expenses:Array.isArray(x.expenses)?x.expenses:[],plan:x.plan||{budget:0,start:null,end:null}}}catch{return{expenses:[],plan:{budget:0,start:null,end:null}}}}
function saveExpense(){localStorage.setItem(KEY,JSON.stringify(state))} function money(n){return Number(n||0).toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2})+' €'} function isoDate(d=new Date()){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)} function parseAmount(v){return Number(String(v).replace(',','.'))} function dateEs(s){if(!s)return '';const[y,m,d]=s.split('-');return `${d}/${m}/${y}`} function dayExpenses(date){return state.expenses.filter(e=>e.date===date).reduce((a,e)=>a+e.amount,0)} function total(){return state.expenses.reduce((a,e)=>a+e.amount,0)} function daysInclusive(a,b){if(!a||!b)return 0;const x=new Date(a+'T00:00:00'),y=new Date(b+'T00:00:00');return y<x?0:Math.floor((y-x)/86400000)+1} function remainingDays(){if(!state.plan.end)return 0;const today=isoDate();return today>state.plan.end?0:daysInclusive(today,state.plan.end)} function periodBudget(){return Number(state.plan.budget||0)} function remainingBudget(){return Math.max(0,periodBudget()-total())}
function dailyBudget(){const{end,start}=state.plan,b=periodBudget();if(!start||!end||b<=0)return 0;const today=isoDate();if(today<start||today>end)return b/daysInclusive(start,end);const spentBefore=state.expenses.filter(e=>e.date>=start&&e.date<today).reduce((a,e)=>a+e.amount,0);return Math.max(0,b-spentBefore)/Math.max(1,daysInclusive(today,end))}
function averageDaily(){if(!state.plan.start)return 0;const today=isoDate();if(today<state.plan.start)return 0;return total()/daysInclusive(state.plan.start,today)}
function pace(){const{start,end}=state.plan,b=periodBudget();if(!start||!end||b<=0)return['—',''];const totalDays=daysInclusive(start,end),today=isoDate();if(today<start)return['Antes del Camino',''];const elapsed=Math.min(totalDays,daysInclusive(start,today)),expected=b*elapsed/totalDays,actual=state.expenses.filter(e=>e.date>=start&&e.date<=today).reduce((a,e)=>a+e.amount,0),ratio=expected?actual/expected:0;if(Math.abs(ratio-1)<=.10)return['→ En ritmo','on'];return ratio>1?['↗ Por encima','high']:['↘ Por debajo','low']}
function renderExpense(){document.getElementById('today').textContent=money(dayExpenses(isoDate()));document.getElementById('average').textContent=money(averageDaily());document.getElementById('total').textContent=money(total());document.getElementById('dailyBudget').textContent=money(dailyBudget());const[p,cls]=pace(),pe=document.getElementById('pace');pe.textContent=p;pe.className='pace '+cls;const b=periodBudget(),t=total();document.getElementById('progressBar').style.width=(b?Math.min(100,t/b*100):0)+'%';document.getElementById('remaining').textContent=`Presupuesto restante: ${money(remainingBudget())}`;document.getElementById('budgetInfo').textContent=b&&state.plan.start&&state.plan.end?`${money(b)} · ${remainingDays()} días restantes · ${dateEs(state.plan.start)} — ${dateEs(state.plan.end)}`:'Configura tu presupuesto y las fechas del Camino.';renderExpenses()}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function renderExpenses(){const box=document.getElementById('expenses'),empty=document.getElementById('empty');box.innerHTML='';[...state.expenses].sort((a,b)=>b.date.localeCompare(a.date)).forEach(e=>{const row=document.createElement('div');row.className='expense';row.innerHTML=`<span class="emoji">${emojis[e.concept]||'🐚'}</span><div class="expense-main"><div class="expense-title">${e.concept.toUpperCase()}</div><div class="expense-sub">${dateEs(e.date)}${e.comment?' · '+escapeHtml(e.comment):''}</div></div><span class="expense-amount">${money(e.amount)}</span><button class="expense-delete" type="button">BORRAR</button>`;row.querySelector('.expense-main').onclick=()=>openExpense(e);row.querySelector('.expense-delete').onclick=()=>{if(confirm('¿Borrar este movimiento?')){state.expenses=state.expenses.filter(x=>x.id!==e.id);saveExpense();renderExpense()}};enableSwipeDelete(row);box.appendChild(row)});empty.style.display=state.expenses.length?'none':'block'}
function enableSwipeDelete(row){let sx=0,sy=0,dx=0,track=false;const reveal=88;row.addEventListener('touchstart',e=>{if(!e.touches.length)return;sx=e.touches[0].clientX;sy=e.touches[0].clientY;dx=0;track=true},{passive:true});row.addEventListener('touchmove',e=>{if(!track||!e.touches.length)return;const x=e.touches[0].clientX,y=e.touches[0].clientY,ax=x-sx,ay=y-sy;if(Math.abs(ay)>Math.abs(ax)+8){track=false;row.style.transform='translateX(0)';return}dx=Math.max(-reveal,Math.min(0,ax));if(ax<0)row.style.transform=`translateX(${dx}px)`},{passive:true});row.addEventListener('touchend',()=>{if(!track)return;track=false;row.style.transform=dx<-40?`translateX(-${reveal}px)`:'translateX(0)';dx=0})}
function openExpense(e=null){editingId=e?.id||null;document.getElementById('expenseDialogTitle').textContent=e?'Editar gasto':'Registrar gasto';document.getElementById('concept').value=e?.concept||'Desayuno';document.getElementById('amount').value=e?String(e.amount).replace('.',','):'';document.getElementById('comment').value=e?.comment||'';document.getElementById('expenseDate').value=e?.date||isoDate();document.getElementById('expenseDialog').showModal()}
function openCategories(){const box=document.getElementById('categorySummaryRows');box.innerHTML='';concepts.forEach(c=>{const sum=state.expenses.filter(e=>e.concept===c).reduce((a,e)=>a+e.amount,0),b=document.createElement('button');b.className='category-modal-row';b.innerHTML=`<span class="emoji">${emojis[c]}</span><span class="name">${c}</span><span class="value">${money(sum)}</span><span>›</span>`;b.onclick=()=>showCategory(c);box.appendChild(b)});document.getElementById('categoryDialog').showModal()}
function showCategory(c){const rows=state.expenses.filter(e=>e.concept===c).sort((a,b)=>b.date.localeCompare(a.date));document.getElementById('categoryTitle').textContent=`${emojis[c]} ${c}`;const box=document.getElementById('categoryRows');box.innerHTML='';if(!rows.length)box.innerHTML='<div class="empty">No hay gastos en esta categoría.</div>';rows.forEach(e=>{const r=document.createElement('div');r.className='cat-row';r.innerHTML=`<div class="cat-detail"><span class="cat-date">${dateEs(e.date)}</span><span class="cat-comment">${escapeHtml(e.comment)||'—'}</span></div><strong>${money(e.amount)}</strong>`;box.appendChild(r)});document.getElementById('categoryDialog').close();document.getElementById('categoryDetailDialog').showModal()}
function openPlan(){document.getElementById('budget').value=state.plan.budget?String(state.plan.budget).replace('.',','):'';document.getElementById('startDate').value=state.plan.start||'';document.getElementById('endDate').value=state.plan.end||'';document.getElementById('planDialog').showModal()}
document.getElementById('newExpenseBtn').onclick=()=>{if(!state.plan.start||!state.plan.end){alert('Primero configura el presupuesto y las fechas.');openPlan();return}openExpense()};document.getElementById('categoriesBtn').onclick=openCategories;
document.getElementById('planBtn')?.addEventListener('click',openPlan);document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());document.getElementById('expenseForm').onsubmit=e=>{e.preventDefault();const amount=parseAmount(document.getElementById('amount').value),date=document.getElementById('expenseDate').value;if(!amount||amount<=0||!date)return;const item={id:editingId||crypto.randomUUID(),concept:document.getElementById('concept').value,comment:document.getElementById('comment').value.trim(),amount,date};if(editingId)state.expenses=state.expenses.map(x=>x.id===editingId?item:x);else state.expenses.push(item);saveExpense();document.getElementById('expenseDialog').close();renderExpense()};document.getElementById('planForm').onsubmit=e=>{e.preventDefault();const budget=parseAmount(document.getElementById('budget').value),start=document.getElementById('startDate').value,end=document.getElementById('endDate').value;if(!budget||!start||!end||end<start){alert('Revisa presupuesto y fechas.');return}state.plan={budget,start,end};saveExpense();document.getElementById('planDialog').close();renderExpense()};document.getElementById('resetPlan').onclick=()=>{if(confirm('¿Restablecer el plan y borrar todos los gastos?')){state={expenses:[],plan:{budget:0,start:null,end:null}};saveExpense();document.getElementById('planDialog').close();renderExpense()}};document.getElementById('exportBtn').onclick=()=>{const rows=[['Fecha','Categoría','Comentario','Importe (€)'],...state.expenses.sort((a,b)=>b.date.localeCompare(a.date)).map(e=>[dateEs(e.date),e.concept,e.comment,e.amount.toFixed(2)])],csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\r\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ultreia_gastos.csv';a.click();URL.revokeObjectURL(a.href)};
renderExpense();

// ---- Seguimiento de Grupo: UX V2 + GPS real ----
const GROUP_KEY='ultreia-group-web-v2';let groupState=loadGroup(),map=null,userMarker=null,groupMarkers=[],watchId=null;
function loadGroup(){try{return JSON.parse(localStorage.getItem(GROUP_KEY))||{alias:'',groupName:'',code:'',sharing:false,position:null,members:[]}}catch{return{alias:'',groupName:'',code:'',sharing:false,position:null,members:[]}}}
function saveGroup(){localStorage.setItem(GROUP_KEY,JSON.stringify(groupState))}
function makeInvite(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let x='';for(let i=0;i<6;i++)x+=chars[Math.floor(Math.random()*chars.length)];return x}
function initMap(){if(map)return;map=L.map('map',{zoomControl:false}).setView([43.36,-8.41],10);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);window._map=map}
function renderGroup(){const box=document.getElementById('groupList');if(!groupState.alias||!groupState.code){box.innerHTML=`<div class="panel"><h3>Seguimiento de Grupo</h3><p>Comparte tu posición con las personas de tu grupo mientras camináis.</p><div class="choice-stack"><button class="primary choice-btn" id="openCreate">👥 Crear un grupo</button><button class="secondary choice-btn" id="openJoin">🔑 Unirse a un grupo</button></div></div>`;document.getElementById('openCreate').onclick=()=>document.getElementById('createGroupDialog').showModal();document.getElementById('openJoin').onclick=()=>document.getElementById('joinGroupDialog').showModal();return}
box.innerHTML=`<div class="panel"><div class="row"><div><div class="small">TU NOMBRE</div><strong>${escapeHtml(groupState.alias)}</strong></div><span class="status ${groupState.sharing?'ok':'warn'}">${groupState.sharing?'Ubicación activa':'Ubicación parada'}</span></div></div><div class="panel"><div class="small">GRUPO</div><h3>${escapeHtml(groupState.groupName)}</h3><div class="group-code"><div class="small" style="color:#fff9">CÓDIGO DE INVITACIÓN</div><strong>${escapeHtml(groupState.code)}</strong></div><div class="row" style="margin-top:12px"><button class="primary" id="shareToggle">${groupState.sharing?'Detener ubicación':'Compartir ubicación'}</button><button class="secondary" id="changeGroup">Cambiar</button></div></div><div class="panel"><h3>Compañeros</h3>${groupState.members.length?groupState.members.map(m=>`<div class="member"><div class="avatar">${escapeHtml((m.alias||'?')[0].toUpperCase())}</div><div><strong>${escapeHtml(m.alias)}</strong><div class="small">${m.lat&&m.lon?'Posición recibida':'Sin posición'}</div></div></div>`).join(''):'<div class="small">Todavía no hay compañeros conectados.</div>'}</div>`;
document.getElementById('shareToggle').onclick=toggleSharing;document.getElementById('changeGroup').onclick=()=>document.getElementById('groupChoiceDialog').showModal()}
function toggleSharing(){groupState.sharing=!groupState.sharing;saveGroup();if(groupState.sharing){if(!navigator.geolocation){alert('Este dispositivo no permite obtener la ubicación.');return}if(watchId==null)watchId=navigator.geolocation.watchPosition(onPosition,geoError,{enableHighAccuracy:true,maximumAge:10000,timeout:15000})}else if(watchId!=null){navigator.geolocation.clearWatch(watchId);watchId=null}renderGroup();showMap()}
function onPosition(pos){const p={lat:pos.coords.latitude,lon:pos.coords.longitude,accuracy:pos.coords.accuracy,updatedAt:Date.now()};groupState.position=p;saveGroup();drawOwn(p);updateMapCard()}
function geoError(e){alert('No se pudo obtener la ubicación: '+e.message)}
function drawOwn(p){initMap();if(!userMarker)userMarker=L.marker([p.lat,p.lon]).addTo(map).bindPopup(`<strong>${escapeHtml(groupState.alias||'Yo')}</strong><br>Mi posición`);else userMarker.setLatLng([p.lat,p.lon]);map.setView([p.lat,p.lon],16)}
function showMap(){document.getElementById('groupList').style.display='none';document.getElementById('mapWrap').style.display='block';initMap();if(groupState.position)drawOwn(groupState.position);updateMapCard()}
function showList(){document.getElementById('mapWrap').style.display='none';document.getElementById('groupList').style.display='block'}
function updateMapCard(){const p=groupState.position;document.getElementById('mapCard').innerHTML=p?`<strong>${escapeHtml(groupState.alias||'Yo')}</strong> · GPS activo<br><span class="small">Precisión aprox. ${Math.round(p.accuracy||0)} m · ${new Date(p.updatedAt).toLocaleTimeString('es-ES')}</span>`:'Activa «Compartir ubicación» para obtener tu posición.'}
document.getElementById('groupMapBtn').onclick=showMap;document.getElementById('groupListBtn').onclick=showList;document.getElementById('locateBtn').onclick=()=>{if(groupState.position)drawOwn(groupState.position);else navigator.geolocation?.getCurrentPosition(onPosition,geoError,{enableHighAccuracy:true})};document.getElementById('refreshGroupBtn').onclick=()=>{renderGroup();if(groupState.position)drawOwn(groupState.position)};
document.getElementById('createGroupForm').onsubmit=e=>{e.preventDefault();groupState.alias=document.getElementById('createAlias').value.trim();groupState.groupName=document.getElementById('createGroupName').value.trim();groupState.code=makeInvite();groupState.sharing=false;saveGroup();document.getElementById('createGroupDialog').close();renderGroup()};
document.getElementById('joinGroupForm').onsubmit=e=>{e.preventDefault();groupState.alias=document.getElementById('joinAlias').value.trim();groupState.code=document.getElementById('joinCode').value.trim().toUpperCase();groupState.groupName='Grupo '+groupState.code;groupState.sharing=false;saveGroup();document.getElementById('joinGroupDialog').close();renderGroup()};
document.getElementById('createGroupBtn').onclick=()=>{document.getElementById('groupChoiceDialog').close();document.getElementById('createGroupDialog').showModal()};document.getElementById('joinGroupBtn').onclick=()=>{document.getElementById('groupChoiceDialog').close();document.getElementById('joinGroupDialog').showModal()};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());
